apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "towerk8-6b5f"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "towerk8-6b5f"
    spec:
      containers:
        - name: "towerk8-6b5f"
          image: "votingacr.azurecr.io/towerk8"
          ports:
          - containerPort: 80